version: 2
jobs:
  test:
    docker:
      - image: circleci/node:14-stretch
    steps:
      - checkout
      - run:
          name: Installing Dependencies
          command: npm install
      - run:
          name: Running Unit Mocha Tests
          command: npm test
workflows:
  version: 2
  build_and_test:
    jobs:
      - test
