version: 2
jobs:
  test:
    docker:
      - image: cimg/node:14.17.5
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Installing Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Running Mocha Tests
          command: npm test
workflows:
  version: 2
  build_and_test:
    jobs:
      - test
